class_name Ability extends Resource

enum UnitTags {GATHER, BUILD, INVISIBILITY, TRUESIGHT, FLIGHT, HERO, UNIQUE}
enum BuildingTags {SPAWNUNIT, TECHUPGRADE, RALLYPOINT, TRUESIGHT, ATTACK, UNIQUE, CAIRN}
